document.writeln("  <div id=\'logo\'><img src=\'image/logo_banner.png\' alt=\'\'></div>");
document.writeln("        <menu id=\'primaryLinks\'>");
document.writeln("            <ul>");
document.writeln("                <li><a href=\'./index.html\'>Home</a></li>");
document.writeln("                <li><a href=\'./time.html\'>TimeLine</a></li>");
document.writeln("                <li><a href=\'./about.html\'>About</a></li>");
document.writeln("                <li class=\'dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropbtn\'>Project2</a>");
document.writeln("                    <div class=\'dropdown-content\'>");
document.writeln("                        <a href=\'./pyLint.html\'>Pylint & OOP</a>");
document.writeln("                        <a href=\'./AAATest.html\'>AAA Test</a>");
document.writeln("                        <a href=\'./calOOP.html\'>Calculator & OOP</a>");
document.writeln("                        <a href=\'./SOLID.html\'>About SOLID</a>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </menu>");